spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:chatServer;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

video:
  uploadPath: /usr/file
  ffmpegPath: /usr/bin/ffmpeg
  ffprobePath: /usr/bin/ffprobe
  staticResourcePath: http://localhost:8080/file/
